<a href="https://colab.research.google.com/github/tu26010-7431-hue/Tu26010/blob/main/Chap02_Ex_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

m = np.ones((5,5), dtype="i") * 3
print(m.dot(m))

[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]
